-- Migration: subject_id HMAC pseudonymization (v2 substrate)
--
-- Context: AILedger posture v2. ledger.decision_events.subject_id is
-- HMAC-SHA256(customer_subject_identifier, per_tenant_salt). This migration
-- creates the per-tenant salt table and the pseudonymization function.
--
-- Defense-in-depth design:
--   - Salts live in ledger.tenant_salts (SEPARATE table from decision_events).
--   - Salt-table access is gated separately from decision_events access.
--     An attacker with read access to decision_events but not to tenant_salts
--     cannot reverse subject_id back to the customer's subject identifier.
--   - The pseudonymize_subject() function uses SECURITY DEFINER so it can
--     read the salt without exposing it to the caller; the caller gets only
--     the HMAC output.
--
-- Idempotent.
--
-- ── OPEN DECISION (Jake review) ────────────────────────────────────────────
-- Salt rotation procedure is NOT YET IMPLEMENTED here. The salt-table schema
-- supports a `superseded_at` column for rotation events, and the function
-- supports lookup-by-current-salt, but the rotation procedure (re-
-- pseudonymizing existing decision_events under a new salt) is a separate
-- one-shot migration to write per-tenant when needed. Flagged in
-- docs/ailedger-threat-model.md §10.3 TD-3 as a Gap.
-- ────────────────────────────────────────────────────────────────────────────

create extension if not exists pgcrypto with schema extensions;

-- ─── tenant_salts table (separate from decision_events) ─────────────────────

create table if not exists ledger.tenant_salts (
  tenant_id      uuid primary key references ledger.tenants(id),
  salt           bytea not null,
    -- 32-byte HMAC salt. Generated by gen_random_bytes(32) at tenant creation.
  created_at     timestamptz not null default now(),
  superseded_at  timestamptz,
    -- Set to now() when salt is rotated. Old salt is retained for re-
    -- pseudonymization of pre-rotation records.
  rotation_note  text
    -- Why the salt was rotated (audit trail).
);

-- Append-only-ish: salts can be created and superseded but rows should not
-- be deleted (deleting a salt orphans all subject_ids generated under it).

create or replace function ledger.tenant_salts_prevent_delete()
returns trigger
language plpgsql
as $$
begin
  raise exception 'ledger.tenant_salts rows cannot be deleted; rotate via supersede instead'
    using errcode = 'P0001';
end;
$$;

drop trigger if exists tenant_salts_no_delete on ledger.tenant_salts;
create trigger tenant_salts_no_delete
  before delete on ledger.tenant_salts
  for each row
  execute function ledger.tenant_salts_prevent_delete();

-- Row-Level Security: salts must be access-gated independently of
-- decision_events. Default DENY; access only through SECURITY DEFINER
-- functions that this migration provides.

alter table ledger.tenant_salts enable row level security;

-- No permissive policy: deny by default. SECURITY DEFINER functions below
-- bypass RLS as needed.

comment on table ledger.tenant_salts is
  'Per-tenant HMAC salts for subject pseudonymization. Access-gated separately '
  'from ledger.decision_events for defense-in-depth: a reader with access to '
  'decision_events but not to tenant_salts cannot reverse subject_id to the '
  'customer-side subject identifier. Salts cannot be deleted; rotation uses '
  'superseded_at + creation of a new row.';

-- ─── pseudonymize_subject() — main function ─────────────────────────────────
-- Input: tenant_id, customer-side subject identifier (text)
-- Output: hex-encoded HMAC-SHA256 of input under per-tenant current salt
--
-- SECURITY DEFINER so the function can read tenant_salts even though the
-- caller can't read it directly. Caller gets only the HMAC output, not the salt.

create or replace function ledger.pseudonymize_subject(
  p_tenant_id uuid,
  p_customer_subject_identifier text
) returns text
language plpgsql
security definer
set search_path = ledger, public, extensions
as $$
declare
  v_salt bytea;
  v_hmac bytea;
begin
  if p_tenant_id is null or p_customer_subject_identifier is null
     or length(p_customer_subject_identifier) = 0 then
    raise exception 'pseudonymize_subject: tenant_id and subject identifier required'
      using errcode = '22023';
  end if;

  -- Use current (non-superseded) salt for this tenant.
  select salt into v_salt
    from ledger.tenant_salts
    where tenant_id = p_tenant_id
      and superseded_at is null;

  if v_salt is null then
    raise exception 'pseudonymize_subject: no current salt for tenant %', p_tenant_id
      using errcode = 'P0002';
  end if;

  v_hmac := extensions.hmac(
    convert_to(p_customer_subject_identifier, 'UTF8'),
    v_salt,
    'sha256'
  );

  return encode(v_hmac, 'hex');
end;
$$;

revoke all on function ledger.pseudonymize_subject(uuid, text) from public;
grant execute on function ledger.pseudonymize_subject(uuid, text)
  to authenticated, service_role;

comment on function ledger.pseudonymize_subject(uuid, text) is
  'HMAC-SHA256 of customer-provided subject identifier under per-tenant salt. '
  'Caller never sees the salt. Output is hex-encoded (64 chars). Used by the '
  'Decision Event ingest path to populate decision_events.subject_id.';

-- ─── Salt provisioning helper (called at tenant creation) ───────────────────

create or replace function ledger.provision_tenant_salt(p_tenant_id uuid)
returns void
language plpgsql
security definer
set search_path = ledger, public, extensions
as $$
begin
  -- Idempotent: do not overwrite existing salt.
  if exists (select 1 from ledger.tenant_salts
             where tenant_id = p_tenant_id and superseded_at is null) then
    return;
  end if;

  insert into ledger.tenant_salts (tenant_id, salt)
    values (p_tenant_id, extensions.gen_random_bytes(32));
end;
$$;

revoke all on function ledger.provision_tenant_salt(uuid) from public;
grant execute on function ledger.provision_tenant_salt(uuid) to service_role;

comment on function ledger.provision_tenant_salt(uuid) is
  'Provisions a 32-byte HMAC salt for a tenant. Idempotent: no-op if a '
  'current (non-superseded) salt already exists. Service-role only.';

-- ─── (Stub) Salt rotation procedure ─────────────────────────────────────────
-- Real rotation requires re-pseudonymizing decision_events.subject_id values
-- under the new salt, which the append-only trigger blocks. The full
-- rotation procedure must:
--   1. Generate new salt, insert into tenant_salts (the current salt's
--      superseded_at column will be set in step 4).
--   2. Read all decision_events for the tenant, recompute subject_id under
--      the new salt (requires the original customer-side subject identifier,
--      which AILedger does NOT store — so re-pseudonymization requires
--      customer cooperation, OR keeping subject_id stable across rotations
--      via a separate cross-walk table).
--   3. (Decision required) Either keep subject_id stable via cross-walk OR
--      accept that subject_id values from before rotation are not linkable
--      to subject_id values after rotation for the same person.
--   4. Mark the old salt superseded_at = now().
--
-- This is documented but NOT IMPLEMENTED here. Flagged in
-- docs/ailedger-threat-model.md §10.3 TD-3 as a gap. Implement when needed
-- (after first paying enterprise customer + before any salt-compromise
-- incident response is required).
